import { RoadmapItem } from './types';

export const OFFICIAL_CURRICULUM: Omit<RoadmapItem, 'id'>[] = [
  // Phase 1: MERN Foundations (Months 1-6)
  { week: 1, module: 'Phase 1', topic: 'HTML5 & Semantic Web', project: 'Basic Web Page', status: 'upcoming', gen: 'all' },
  { week: 2, module: 'Phase 1', topic: 'CSS3, Flexbox, & Grid', project: 'Responsive Portfolio Page', status: 'upcoming', gen: 'all' },
  { week: 3, module: 'Phase 1', topic: 'JavaScript ES6+ Basics', project: 'Interactive Calculator', status: 'upcoming', gen: 'all' },
  { week: 4, module: 'Phase 1', topic: 'DOM Manipulation & Events', project: 'To-Do List App', status: 'upcoming', gen: 'all' },
  { week: 5, module: 'Phase 1', topic: 'Async JS & API Fetching', project: 'Weather Dashboard', status: 'upcoming', gen: 'all' },
  { week: 6, module: 'Phase 1', topic: 'React Fundamentals & JSX', project: 'React Profile Card', status: 'upcoming', gen: 'all' },
  { week: 7, module: 'Phase 1', topic: 'React State & Props', project: 'Interactive Quiz App', status: 'upcoming', gen: 'all' },
  { week: 8, module: 'Phase 1', topic: 'React Hooks (useEffect, useRef)', project: 'Movie Search App', status: 'upcoming', gen: 'all' },
  { week: 9, module: 'Phase 1', topic: 'React Router & Navigation', project: 'Multi-page React App', status: 'upcoming', gen: 'all' },
  { week: 10, module: 'Phase 1', topic: 'React Forms & Axios', project: 'React CRUD Frontend', status: 'upcoming', gen: 'all' },
  { week: 11, module: 'Phase 1', topic: 'AI Tools Intro: Cursor & Copilot', project: 'Refactor Week 5-10 with AI', status: 'upcoming', gen: 'all' },
  { week: 12, module: 'Phase 1', topic: 'Node.js Basics & NPM', project: 'Simple CLI Tool', status: 'upcoming', gen: 'all' },
  { week: 13, module: 'Phase 1', topic: 'Express.js & RESTful APIs', project: 'Basic Express Server', status: 'upcoming', gen: 'all' },
  { week: 14, module: 'Phase 1', topic: 'Authentication & JWT', project: 'Auth API with Login/Register', status: 'upcoming', gen: 'all' },
  { week: 15, module: 'Phase 1', topic: 'MongoDB Basics', project: 'Database Schema Design', status: 'upcoming', gen: 'all' },
  { week: 16, module: 'Phase 1', topic: 'Mongoose & Data Modeling', project: 'Mongoose CRUD Operations', status: 'upcoming', gen: 'all' },
  { week: 17, module: 'Phase 1', topic: 'Full MERN Integration', project: 'Fullstack Task Manager', status: 'upcoming', gen: 'all' },
  { week: 18, module: 'Phase 1', topic: 'State Management (Redux/Zustand)', project: 'E-commerce Cart System', status: 'upcoming', gen: 'all' },
  { week: 19, module: 'Phase 1', topic: 'Deployment & Env Config', project: 'Deploy MERN App to Production', status: 'upcoming', gen: 'all' },
  { week: 20, module: 'Phase 1', topic: 'Error Handling & Validation', project: 'Robust API Validation', status: 'upcoming', gen: 'all' },
  { week: 21, module: 'Phase 1', topic: 'Testing Basics (Jest/React Testing)', project: 'Unit Tests for MERN App', status: 'upcoming', gen: 'all' },
  { week: 22, module: 'Phase 1', topic: 'Code Quality & Polish', project: 'Code Review & Refactoring', status: 'upcoming', gen: 'all' },
  { week: 23, module: 'Phase 1', topic: 'Milestone 1 Prep', project: 'Milestone 1 Project Completion', status: 'upcoming', gen: 'all' },
  { week: 24, module: 'Phase 1', topic: 'Milestone 1 Assessment', project: 'Live Demo + Code Walkthrough', status: 'upcoming', gen: 'all' },

  // Phase 2: Advanced MERN + AI Engineering (Months 7-12)
  { week: 25, module: 'Phase 2', topic: 'TypeScript Fundamentals', project: 'TS Utility Library', status: 'upcoming', gen: 'all' },
  { week: 26, module: 'Phase 2', topic: 'Typed React Components', project: 'Refactor React App to TS', status: 'upcoming', gen: 'all' },
  { week: 27, module: 'Phase 2', topic: 'Advanced Node/Express with TS', project: 'Secure TS API', status: 'upcoming', gen: 'all' },
  { week: 28, module: 'Phase 2', topic: 'Backend Architecture Patterns', project: 'API with Service Layer', status: 'upcoming', gen: 'all' },
  { week: 29, module: 'Phase 2', topic: 'PostgreSQL & Prisma ORM', project: 'SQL Database Integration', status: 'upcoming', gen: 'all' },
  { week: 30, module: 'Phase 2', topic: 'WebSockets & Real-time Apps', project: 'Real-time Chat App', status: 'upcoming', gen: 'all' },
  { week: 31, module: 'Phase 2', topic: 'Intro to LLM APIs (OpenAI/Anthropic)', project: 'Basic AI Chat Interface', status: 'upcoming', gen: 'all' },
  { week: 32, module: 'Phase 2', topic: 'Prompt Engineering & Streaming', project: 'Streaming Chatbot in React', status: 'upcoming', gen: 'all' },
  { week: 33, module: 'Phase 2', topic: 'Python Reading Unit', project: 'Python Fundamentals Script', status: 'upcoming', gen: 'all' },
  { week: 34, module: 'Phase 2', topic: 'Embeddings & Vector Databases', project: 'Vector Search Implementation', status: 'upcoming', gen: 'all' },
  { week: 35, module: 'Phase 2', topic: 'RAG Pipeline Construction', project: 'Document Q&A System', status: 'upcoming', gen: 'all' },
  { week: 36, module: 'Phase 2', topic: 'LangChain & Frameworks', project: 'LangChain Orchestration', status: 'upcoming', gen: 'all' },
  { week: 37, module: 'Phase 2', topic: 'AI Agents & Tool Use', project: 'Agent with 2+ Tool Integrations', status: 'upcoming', gen: 'all' },
  { week: 38, module: 'Phase 2', topic: 'Function Calling Integration', project: 'AI triggering API actions', status: 'upcoming', gen: 'all' },
  { week: 39, module: 'Phase 2', topic: 'No-Code/Low-Code Tools (n8n/Make)', project: 'Basic Automation Flow', status: 'upcoming', gen: 'all' },
  { week: 40, module: 'Phase 2', topic: 'Workflow Design & Automation', project: 'Automated Business Workflow', status: 'upcoming', gen: 'all' },
  { week: 41, module: 'Phase 2', topic: 'Next.js App Router', project: 'Next.js SEO App', status: 'upcoming', gen: 'all' },
  { week: 42, module: 'Phase 2', topic: 'Next.js Server Actions', project: 'Fullstack Next.js App', status: 'upcoming', gen: 'all' },
  { week: 43, module: 'Phase 2', topic: 'Milestone 2 Design Sprint', project: 'AI Product System Design', status: 'upcoming', gen: 'all' },
  { week: 44, module: 'Phase 2', topic: 'Milestone 2 Build Phase 1', project: 'Core AI Features', status: 'upcoming', gen: 'all' },
  { week: 45, module: 'Phase 2', topic: 'Milestone 2 Build Phase 2', project: 'Frontend & UI Polish', status: 'upcoming', gen: 'all' },
  { week: 46, module: 'Phase 2', topic: 'Production Hardening & CI/CD', project: 'Automated Deployment Pipeline', status: 'upcoming', gen: 'all' },
  { week: 47, module: 'Phase 2', topic: 'Milestone 2 Polish', project: 'Milestone 2 Project Hardened', status: 'upcoming', gen: 'all' },
  { week: 48, module: 'Phase 2', topic: 'Milestone 2 Assessment', project: 'Pass: 70% Overall', status: 'upcoming', gen: 'all' },

  // Phase 3: Advanced AI Systems + Production Readiness (Months 13-18)
  { week: 49, module: 'Phase 3', topic: 'Multi-agent Orchestration', project: 'Multi-agent System Design', status: 'upcoming', gen: 'all' },
  { week: 50, module: 'Phase 3', topic: 'Memory Patterns in AI', project: 'Long-term Agent Memory', status: 'upcoming', gen: 'all' },
  { week: 51, module: 'Phase 3', topic: 'AI Product Design & UX', project: 'AI Product Critique & Redesign', status: 'upcoming', gen: 'all' },
  { week: 52, module: 'Phase 3', topic: 'AI Ethics & Alignment', project: 'Ethical Guidelines Report', status: 'upcoming', gen: 'all' },
  { week: 53, module: 'Phase 3', topic: 'Microservices Architecture', project: 'Deconstruct Monolith', status: 'upcoming', gen: 'all' },
  { week: 54, module: 'Phase 3', topic: 'Docker & Containerization', project: 'Dockerize Next.js & Node App', status: 'upcoming', gen: 'all' },
  { week: 55, module: 'Phase 3', topic: 'Cloud Infrastructure (AWS/GCP)', project: 'Deploy via Containers', status: 'upcoming', gen: 'all' },
  { week: 56, module: 'Phase 3', topic: 'Evals & Monitoring', project: 'Eval Suite for AI Product', status: 'upcoming', gen: 'all' },
  { week: 57, module: 'Phase 3', topic: 'Observability (LangSmith/Datadog)', project: 'Agent Traceability Implementation', status: 'upcoming', gen: 'all' },
  { week: 58, module: 'Phase 3', topic: 'Data Literacy: Ground-truth Datasets', project: 'Audit Product Data Quality', status: 'upcoming', gen: 'all' },
  { week: 59, module: 'Phase 3', topic: 'Caching with Redis', project: 'Implement API Caching layer', status: 'upcoming', gen: 'all' },
  { week: 60, module: 'Phase 3', topic: 'Advanced Security & Rate Limiting', project: 'Secure Architecture Implementation', status: 'upcoming', gen: 'all' },
  { week: 61, module: 'Phase 3', topic: 'Production Hardening', project: 'Harden Phase 2 Product', status: 'upcoming', gen: 'all' },
  { week: 62, module: 'Phase 3', topic: 'Vibe Coding: Specs to System', project: 'Direct-to-Instructor Demo', status: 'upcoming', gen: 'all' },
  { week: 63, module: 'Phase 3', topic: 'Performance Optimization', project: 'Web Vitals & Backend Scaling', status: 'upcoming', gen: 'all' },
  { week: 64, module: 'Phase 3', topic: 'Milestone 3 Capstone Pitch', project: 'Project Proposal Approval', status: 'upcoming', gen: 'all' },
  { week: 65, module: 'Phase 3', topic: 'Milestone 3 Core Backend', project: 'Capstone API & AI Logic', status: 'upcoming', gen: 'all' },
  { week: 66, module: 'Phase 3', topic: 'Milestone 3 Core Frontend', project: 'Capstone UI implementation', status: 'upcoming', gen: 'all' },
  { week: 67, module: 'Phase 3', topic: 'Milestone 3 System Integration', project: 'Full System Testing', status: 'upcoming', gen: 'all' },
  { week: 68, module: 'Phase 3', topic: 'Milestone 3 Launch Prep', project: 'Production AI System Deployment', status: 'upcoming', gen: 'all' },
  { week: 69, module: 'Phase 3', topic: 'Career Preparation', project: 'Resume & LinkedIn Review', status: 'upcoming', gen: 'all' },
  { week: 70, module: 'Phase 3', topic: 'GitHub Portfolio Polish', project: 'Open Source Contributions', status: 'upcoming', gen: 'all' },
  { week: 71, module: 'Phase 3', topic: 'Mock Technical Interviews', project: 'Mock Interview with External Dev', status: 'upcoming', gen: 'all' },
  { week: 72, module: 'Phase 3', topic: 'Milestone 3 Assessment Week', project: 'Graduation Gate', status: 'upcoming', gen: 'all' }
];
